"""Общие тексты бота (правила роутера, ошибки, общие кнопки).

Текстовые значения вынесены в yaml/common.yaml.
"""
from app.bot.texts.loader import load_texts

_D = load_texts("common.yaml")

WELCOME: str = _D["WELCOME"]

ERROR: str = _D["ERROR"]
STALE_BUTTON: str = _D["STALE_BUTTON"]
FINISH_REG_FIRST: str = _D["FINISH_REG_FIRST"]
CONTINUE_REG: str = _D["CONTINUE_REG"]
REG_CANCEL_HINT: str = _D["REG_CANCEL_HINT"]
UNSUPPORTED: str = _D["UNSUPPORTED"]
UNKNOWN_COMMAND: str = _D["UNKNOWN_COMMAND"]
SUB_CANCELLED: str = _D["SUB_CANCELLED"]
PROFILE_CANCELLED: str = _D["PROFILE_CANCELLED"]
SUB_EXPIRED: str = _D["SUB_EXPIRED"]
PROFILE_EXPIRED: str = _D["PROFILE_EXPIRED"]
PHOTO_SAVED: str = _D["PHOTO_SAVED"]
PHOTO_REPLACED_PENDING: str = _D["PHOTO_REPLACED_PENDING"]
PHOTO_FAILED: str = _D["PHOTO_FAILED"]
FIRST_PHOTO_ONLY: str = _D["FIRST_PHOTO_ONLY"]

BTN_RETRY: str = _D["BTN_RETRY"]
BTN_MENU: str = _D["BTN_MENU"]
BTN_RESTART: str = _D["BTN_RESTART"]
BTN_CONTINUE: str = _D["BTN_CONTINUE"]
BTN_BACK: str = _D["BTN_BACK"]
BTN_CANCEL: str = _D["BTN_CANCEL"]
BTN_MINIAPP: str = _D["BTN_MINIAPP"]

MENU_WORDS: set[str] = set(_D["MENU_WORDS"])
CANCEL_WORDS: set[str] = set(_D["CANCEL_WORDS"])
SUB_CANCELLED_BY_USER: str = _D["SUB_CANCELLED_BY_USER"]
PROFILE_CANCELLED_BY_USER: str = _D["PROFILE_CANCELLED_BY_USER"]
