"""Тексты меню-дашборда и экранов из меню (поток S4).

Текстовые значения вынесены в yaml/menu.yaml.
"""
from app.bot.texts.loader import load_texts

_D = load_texts("menu.yaml")

# --- Дашборд ---
PERIOD_OPEN: str = _D["PERIOD_OPEN"]
PERIOD_NEXT: str = _D["PERIOD_NEXT"]
METER_SUBMITTED: str = _D["METER_SUBMITTED"]
METER_NOT_SUBMITTED: str = _D["METER_NOT_SUBMITTED"]
METERS_SUMMARY: str = _D["METERS_SUMMARY"]
METERS_ALL_DONE: str = _D["METERS_ALL_DONE"]
NO_METERS: str = _D["NO_METERS"]
VERIFICATION: str = _D["VERIFICATION"]
VERIFICATION_OVERDUE: str = _D["VERIFICATION_OVERDUE"]
MORE: str = _D["MORE"]
BILL: str = _D["BILL"]
BILL_OVERDUE: str = _D["BILL_OVERDUE"]
BILLS: str = _D["BILLS"]
DEMO_MARK: str = _D["DEMO_MARK"]
BILL_NOTE: str = _D["BILL_NOTE"]
PENDING: str = _D["PENDING"]
PENDING_MANY: str = _D["PENDING_MANY"]
FOOTER: str = _D["FOOTER"]

# --- Срочное действие ---
URGENT_VERIFICATION: str = _D["URGENT_VERIFICATION"]
URGENT_VERIFICATION_TODAY: str = _D["URGENT_VERIFICATION_TODAY"]
URGENT_VERIFICATION_OVERDUE: str = _D["URGENT_VERIFICATION_OVERDUE"]
URGENT_BILL: str = _D["URGENT_BILL"]
URGENT_BILL_TODAY: str = _D["URGENT_BILL_TODAY"]
URGENT_BILL_OVERDUE: str = _D["URGENT_BILL_OVERDUE"]
URGENT_SUBMIT: str = _D["URGENT_SUBMIT"]
URGENT_SUBMIT_TODAY: str = _D["URGENT_SUBMIT_TODAY"]

# --- Кнопки меню ---
BTN_SUBMIT: str = _D["BTN_SUBMIT"]
BTN_METERS: str = _D["BTN_METERS"]
BTN_PROFILE: str = _D["BTN_PROFILE"]
BTN_ADD_METER: str = _D["BTN_ADD_METER"]

# --- Мои счётчики ---
METERS_TITLE: str = _D["METERS_TITLE"]
METERS_LAST: str = _D["METERS_LAST"]
METERS_NO_READINGS: str = _D["METERS_NO_READINGS"]
METERS_VERIFICATION: str = _D["METERS_VERIFICATION"]
METERS_PENDING: str = _D["METERS_PENDING"]

# --- Честные заглушки ---
VERIFICATION_STUB: str = _D["VERIFICATION_STUB"]
PAY_STUB: str = _D["PAY_STUB"]
